name: conditional-steps-1
on: workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo "Step 1"
      - name: step-2
        run: exit 1
      - name: step-3
        if: always()
        run: echo "Step 3 (runs even if a previous step fails)"
