name: conditional-steps-3
on: workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo "Step 1"
      - name: step-2
        run: echo "Step 2 fails" && exit 1
      - name: step-3
        if: cancelled()
        run: echo "Step 3 (runs only if workflow has been cancelled)"
