name: conditional-jobs-3
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "I'm Job 1"
  job-2:
    needs: job-1
    if: github.event.sender.login == 'weibeld'
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "I run only if workflow triggered by 'weibeld'"
  job-3:
    needs: job-1
    if: github.event.sender.login == 'foobar'
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "I run only if workflow triggered by 'foobar'"
