name: conditional-jobs-5
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: exit 1
  job-2:
    needs: job-1
    if: always() && github.event.sender.login == 'weibeld'
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "I run only if workflow triggered by 'weibeld' (and Job 1 succeeds)"
  job-3:
    needs: job-1
    if: always() && github.event.sender.login == 'foobar'
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "I run only if workflow triggered by 'foobar' (and Job 1 succeeds)"
