name: conditional-jobs-3
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: exit 1
  job-2:
    needs: job-1
    if: github.event.sender.login == 'weibeld'
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: "I'm Job 2"
