name: dependencies-1
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "I'm Job 1"
  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "I'm Job 2"
